name: "Gatsby Build"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm i
      - name: Run Tests
        run: npm run test

  github-pages:
    name: GitHub Pages
    runs-on: ubuntu-latest
    if: ${{ success() && !startsWith(github.ref, 'refs/pull') }}
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm i
      - name: Build Static Site
        run: npm run build
      - name: Publish Static Site
        uses: jamesives/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages
          FOLDER: public